name: Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4
 
      # Push to hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://toan215:$HF_TOKEN@huggingface.co/spaces/toan215/Meta-Meal
          git push -f hf main
